management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true

  endpoint:
    shutdown:
      enabled: true
    health:
      # showDetails: always
      showComponents: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: yh

logging:
  level:
    hello.controller: debug